DoXin/DoXin.Web/Controllers/CompanyTypesController.cs
using Doxin.Core.models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DoxIn.Web.Controllers
{
    public class CompanyTypesController : Controller
    {
        private CommonEntity db = new CommonEntity();

        // GET: CompanyTypes
        public async Task<ActionResult> Index()
        {
            ViewBag.ErrorMessage = TempData["ErrorMessage"];
            ViewBag.Operation = TempData["Operation"];
            ViewBag.Success = TempData["Success"];
            return View(await db.CompanyTypes.ToListAsync());
        }

        // GET: CompanyTypes/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyType companyType = await db.CompanyTypes.FindAsync(id);
            if (companyType == null)
            {
                return HttpNotFound();
            }
            return View(companyType);
        }

        // GET: CompanyTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompanyTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CT_ID,CT_CompanyType")] CompanyType companyType)
        {
            if (ModelState.IsValid)
            {
                companyType.CT_ID = Guid.NewGuid();
                db.CompanyTypes.Add(companyType);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(companyType);
        }

        // GET: CompanyTypes/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompanyType companyType = await db.CompanyTypes.FindAsync(id);
            if (companyType == null)
            {
                return HttpNotFound();
            }
            return View(companyType);
        }

        // POST: CompanyTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "CT_ID,CT_CompanyType")] CompanyType companyType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(companyType).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(companyType);
        }

        // GET: CompanyTypes/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ct = db.CompanyTypes.Find(id);
            var inUse = (from c in db.Companies
                         where (c.CO_CompanyType.CT_CompanyType == ct.CT_CompanyType)
                         select c.CO_ID).ToList();
            if (inUse.Count > 0)
            {
                TempData["ErrorMessage"] = "Unable to Delete when Company Type is in use";
                TempData["Operation"] = "Failed to Delete Company Type";
            }
            else
            {
                db.CompanyTypes.Remove(ct);
                await db.SaveChangesAsync();
                TempData["ErrorMessage"] = "Company Type Deleted successfully";
                TempData["Operation"] = "Delete Company Type";
                TempData["Success"] = "true";
            }

            return RedirectToAction("Index");


        }

        // POST: CompanyTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            CompanyType companyType = await db.CompanyTypes.FindAsync(id);
            db.CompanyTypes.Remove(companyType);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoXin/DoXin.Web/Views/CompanyTypes/Create.cshtml
@model Doxin.Core.models.CompanyType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CT_CompanyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CT_CompanyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CT_CompanyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoXin/DoXin.Web/Views/CompanyTypes/Delete.cshtml
@model Doxin.Core.models.CompanyType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CT_CompanyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CT_CompanyType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DoXin/DoXin.Web/Views/CompanyTypes/Details.cshtml
@model Doxin.Core.models.CompanyType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CompanyType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CT_CompanyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CT_CompanyType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CT_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DoXin/DoXin.Web/Views/CompanyTypes/Edit.cshtml
@model Doxin.Core.models.CompanyType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompanyType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CT_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CT_CompanyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CT_CompanyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CT_CompanyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DoXin/DoXin.Web/Views/CompanyTypes/Index.cshtml
@model IEnumerable<Doxin.Core.models.CompanyType>

@{
    ViewBag.Title = "Company Type Listing";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section styles {
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
}
@section scripts {
    <script type="text/javascript" src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">

    </script>
    <script>
        $(document).ready(function () {
            $('#companyTypeList').DataTable(
                {
                    stateSave: true,
                    "scrollY": "600px",
                    "scrollCollapse": true,
                    "columnDefs": [{ "width": "5%", "targets": 0 },
                        {"width":"30%"}
                    ]
                }
            );
        });
    </script>
    <script>
        $(document).on('click', '#companyTypeList tbody tr', function (event) {
            $(this).addClass('highlight').siblings().removeClass('highlight');
        });
    </script>
}
<h2>Company Types</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new {@class="btn btn-info" })
</p>
<div class="container">
    <div class="col col-md-10">
        <table id="companyTypeList" class="display table table-hover" style="width:75%">
            <thead>
                <tr>
                    <th scope="col" class="col-sm-2"> </th>
                    <th scope="col" class="col-md-12"> @Html.DisplayNameFor(model => model.CT_CompanyType)</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="@Url.Action("Edit", "CompanyTypes", new { id = item.CT_ID }, null)"><i class="fas fa-angle-double-right" style="color:dodgerblue"></i>&nbsp;</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CT_CompanyType)
                        </td>
                        <th>
                            <a href="@Url.Action("Delete", "CompanyTypes", new { id = item.CT_ID }, null)"><i class="fas fa-trash-alt" style="color:darkred"></i>&nbsp;</a>
                        </th>
                    </tr>
                }
            </tbody>

        </table>
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        string cardType = ViewBag.Success == "true"? "border border-success mb-3" : "border border-warning mb-3";

        string header = ViewBag.Success == "true"? "Successfull" : "Warning";
        <div class="@cardType" >

            <div class="card-header">@header</div>
            <div class="card-body">
                <h4 class="card-title">@ViewBag.Operation</h4>
                <p class="card-text">@ViewBag.ErrorMessage</p>
            </div>
        </div>
    }

</div>