DoXin/DoXin.Web/Controllers/CustomersController.cs
using Doxin.Core.models;
using DoXin.Infrastructure.dto;
using DoXin.Infrastructure.interfaces;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace DoxIn.Web.Controllers
{
    public class CustomersController : Controller
    {
        private CommonEntity db = new CommonEntity();

        // GET: Customers
        public ActionResult Index()
        {
            return View(db.Customers.ToList());
        }

        // GET: Customers/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "CU_ID,CU_CODE,CU_NAME,CU_ACTIVE,CU_ADDRESS1,CU_ADDRESS2,CU_ADDRESS3,CU_CITY,CU_PHONE,CU_EMAIL,CU_INCOMINGCODE")] Customer customer)
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                using (IUnitOfWork uow = new UnitOfWork(new CommonEntity()))
                {
                    uow.Customers.Add(customer);
                    uow.Complete();
                }

                //customer.CU_ID = Guid.NewGuid();
                //db.Customers.Add(customer);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                using (IUnitOfWork uow = new UnitOfWork(new CommonEntity()))
                {
                    var cust = uow.Customers.Get(customer.CU_ID);
                    if (cust != null)
                    {
                        cust.CU_ACTIVE = customer.CU_ACTIVE;
                        cust.CU_ADDRESS1 = customer.CU_ADDRESS1;
                        cust.CU_ADDRESS2 = customer.CU_ADDRESS2;
                        cust.CU_ADDRESS3 = customer.CU_ADDRESS3;
                        cust.CU_CITY = customer.CU_CITY;
                        cust.CU_CODE = customer.CU_CODE;
                        cust.CU_EMAIL = customer.CU_EMAIL;
                        cust.CU_INCOMINGCODE = customer.CU_INCOMINGCODE;
                        cust.CU_NAME = customer.CU_NAME;
                        cust.CU_PHONE = customer.CU_PHONE;
                        cust.CU_POSTCODE = customer.CU_POSTCODE;
                        cust.CU_STATE = customer.CU_STATE;
                        uow.Complete();
                    }
                }
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoXin/DoXin.Web/Controllers/DateTypesController.cs
using Doxin.Core.models;
using System;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DoxIn.Web.Controllers
{
    public class DateTypesController : Controller
    {
        private CommonEntity db = new CommonEntity();

        // GET: DateTypes
        public async Task<ActionResult> Index()
        {
            return View(await db.DateTypes.ToListAsync());
        }

        // GET: DateTypes/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DateType dateType = await db.DateTypes.FindAsync(id);
            if (dateType == null)
            {
                return HttpNotFound();
            }
            return View(dateType);
        }

        // GET: DateTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DateTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DT_Id,DT_Name,DT_DateType")] DateType dateType)
        {
            if (ModelState.IsValid)
            {
                dateType.DT_Id = Guid.NewGuid();
                db.DateTypes.Add(dateType);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(dateType);
        }

        // GET: DateTypes/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DateType dateType = await db.DateTypes.FindAsync(id);
            if (dateType == null)
            {
                return HttpNotFound();
            }
            return View(dateType);
        }

        // POST: DateTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "DT_Id,DT_Name,DT_DateType")] DateType dateType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dateType).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(dateType);
        }

        // GET: DateTypes/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DateType dateType = await db.DateTypes.FindAsync(id);
            if (dateType == null)
            {
                return HttpNotFound();
            }
            return View(dateType);
        }

        // POST: DateTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            DateType dateType = await db.DateTypes.FindAsync(id);
            db.DateTypes.Remove(dateType);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoXin/DoXin.Web/Views/Shared/_AdminMenu.cshtml
@using DoxIn.Web.Helpers
<nav id="sidebar">
    <div class="sidebar-header">
        <img src="/images/Doxin-Logo-small.png" alt="DoXin by CTC">
        <h4>By CTC</h4>
    </div>
    <ul class="nav flex-column">
        <p>Administration</p>
        <li class="@Html.IsSelected(actions: "Index", controllers: "Admin")">
            <a href="@Url.Action("Index","Admin")">
                <i class="fas fa-home"></i>Home
            </a>

        </li>
        <li class="@Html.IsSelected(actions: "Details,Index,UpdateCompany,UpdateHeader,UpdateDates,UpdateLine", controllers: "ConvertedFiles")">
            <a href="@Url.Action("Index","Customers")">
                <i class="fas fa-file-import"></i>
                Customers
            </a>
        </li>
        <li class="@Html.IsSelected(actions: "Create,Details,Edit, Index", controllers: "Account")">
            <a href="@Url.Action("ListUsers","Account")"><i class="fas fa-users"></i> Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed text-truncate" href="#submenu1" data-toggle="collapse" data-target="#submenu1"><i class="fas fa-cogs"></i> Settings</a>
            <div class="collapse" id="submenu1" aria-expanded="false">
                <ul class="flex-column pl-2 nav">
                    <li class="nav-item @Html.IsSelected(actions: "CompanyTypes", controllers: "Admin")">
                        <a href="@Url.Action("Index","CompanyTypes")"><i class="fas fa-building"></i> Company Types</a>
                    </li>
                    <li class="nav-item @Html.IsSelected(actions: "DataTypes", controllers: "Admin")">
                        <a href="@Url.Action("Index","DateTypes")"><i class="fas fa-calendar-check"></i> Date Types</a>
                    </li>
                    <li class="@Html.IsSelected(actions: "Roles", controllers: "Admin")">
                        <a href="@Url.Action("ListRoles","Account")"><i class="fas fa-user-shield"></i> Security Roles</a>
                    </li>

                </ul>

            </div>
        </li>
        

        <li>
            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                @Html.AntiForgeryToken()
                <a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="fas fa-sign-out-alt"></i>
                    Log Out

                </a>
            }

        </li>
       
    </ul>
</nav>

DoXin/DoXin.Web/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - By CTC</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://kit.fontawesome.com/7f456184fc.js" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)

    @RenderSection("styles", required: false)

</head>
<body>
    <div class="wrapper">
        @*@if (User.IsInRole("DoXinAdmin"))
        {
            @Html.Partial("_AdminMenu")
        }
        @if (User.IsInRole("User"))
        {

            @Html.Partial("_NavMenu")
        }*@

        @*<div id="content">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">

                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>

                    </div>
                </nav>
            </div>*@
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - DoXin By CTC</p>
            </footer>
        </div>
    </div>





    <script type="text/javascript">
        $(document).ready(function () {

            $('sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        });
    </script>

</body>
</html>

DoXin/DoXin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - By CTC</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://kit.fontawesome.com/7f456184fc.js" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)

    @RenderSection("styles", required: false)

</head>
<body>
    <div class="wrapper">
        @if (User.IsInRole("DoXinAdmin"))
        {
            @Html.Partial("_AdminMenu")
        }
        @if (User.IsInRole("User")|| User.IsInRole("DoXinUser"))
        {

            @Html.Partial("_NavMenu")
        }

        @*<div id="content">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">

                        <button type="button" id="sidebarCollapse" class="btn btn-info">
                            <i class="fas fa-align-left"></i>
                            <span>Toggle Sidebar</span>
                        </button>

                    </div>
                </nav>
            </div>*@
        <div class="container body-content">
            @RenderBody()
            <hr />

        </div>
    </div>
    <footer class="ctcfooter">
        &copy; @DateTime.Now.Year - DoXin By CTC
    </footer>




    <script type="text/javascript">
        $(document).ready(function () {

            $('sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        });
    </script>

</body>
</html>

DoXin/DoXin.Web/Views/Shared/_NavMenu.cshtml
@using DoxIn.Web.Helpers
<nav id="sidebar">
    <div class="sidebar-header">
        <img src="/images/Doxin-Logo-small.png" alt="DoXin by CTC">
        <h4>By CTC</h4>
    </div>
    <ul class="list-unstyled components">
        <p>Navigation</p>
        <li class="@Html.IsSelected(actions: "Index", controllers: "Home")">           
            <a href="@Url.Action("Index","Home")">
                <i class="fas fa-home"></i>Home
            </a>

        </li>
        <li class="@Html.IsSelected(actions: "Details,Index,UpdateCompany,UpdateHeader,UpdateDates,UpdateLine", controllers: "ConvertedFiles")">
            <a href="@Url.Action("Index","ConvertedFiles")">
                <i class="fas fa-file-import"></i>
                </i>Conversions
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fas fa-question-circle"></i>
                Help
            </a>
        </li>
        <li>
            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                @Html.AntiForgeryToken()
                <a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="fas fa-sign-out-alt"></i>
                    Log Out

                </a>
            }

        </li>
       

    </ul>
</nav>

DoXin/DoXin.Web/Views/Shared/_NavMenuNoLogo.cshtml
@using DoxIn.Web.Helpers
<nav id="sidebar">
    @*<div class="sidebar-header">
        <img src="/images/Doxin-Logo-small.png" alt="DoXin by CTC">
        <h4>By CTC</h4>
    </div>*@
    <ul class="list-unstyled components">
        <p>Navigation</p>
        <li class="@Html.IsSelected(actions: "Index", controllers: "Home")">
            <a href="@Url.Action("Index","Home")">
                <i class="fas fa-home"></i>Home
            </a>

        </li>
        <li class="@Html.IsSelected(actions: "Details,Index,UpdateCompany,UpdateHeader,UpdateDates,UpdateLine", controllers: "ConvertedFiles")">
            <a href="@Url.Action("Index","ConvertedFiles")">
                <i class="fas fa-file-import"></i>
                </i>Conversions
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fas fa-question-circle"></i>
                Help
            </a>
        </li>
        <li>
            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
            {
                @Html.AntiForgeryToken()
                <a href="javascript:document.getElementById('logoutForm').submit()">
                    <i class="fas fa-sign-out-alt"></i>
                    Log Out

                </a>
            }

        </li>


    </ul>
</nav>

DoXin/DoXin.Web/Views/Shared/_StatusMessages.cshtml
@model DoxIn.Web.Models.ApplicationStatusMessage

@if (!string.IsNullOrEmpty(Model.Message))
{
    string cardType = Model.Success ? "border border-success mb-3" : "border border-warning mb-3";

    string header = Model.Success ? "Successfull" : "Warning";
    <div class="@cardType">

        <div class="card-header">@header</div>
        <div class="card-body">
            <h4 class="card-title">@Model.Operation</h4>
            <p class="card-text">@Model.Message</p>
        </div>
    </div>
}

DoXin/DoXin.Web/Views/Shared/_UpdateDataLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - By CTC</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://kit.fontawesome.com/7f456184fc.js" crossorigin="anonymous"></script>
    @RenderSection("scripts", required: false)

    @RenderSection("styles", required: false)

</head>
<body>
    <nav class=" bg-ctc navbar navbar-expand-lg">
        <a class="navbar-brand" href="#"><img src="~/images/Doxin-Logo-small.png" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>

    </nav>
    <div class="wrapper">
        @Html.Partial("_NavMenuNoLogo")
        <div class="container body-content">
            @RenderBody()
            <hr />

        </div>

    </div>





    <footer class="ctcfooter">
        &copy; @DateTime.Now.Year - DoXin By CTC
    </footer>



    <script type="text/javascript">
        $(document).ready(function () {

            $('sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

        });
    </script>

</body>
</html>